### ISSUE TITLE
dict object has no attribute iteritems/ a bytes-like object is required, not 'str' 

### ISSUE THREAD

**Issue by YenChunLin** [rwb27/usaf_analysis#2]
in python3 , use **dict.items()** instead of **dict.iteritems()**

in **for p in maker_note.split(" "):** 
use **for p in maker_note.decode().split(" "):** 
[dump_exif.txt](https://github.com/rwb27/usaf_analysis/files/1575788/dump_exif.txt)

**Comment by rwb27** [comment]
I've included this in 10f7c18
