### ISSUE TITLE
Edited scripts to capture raw images

### ISSUE THREAD

**Issue by YenChunLin** [rwb27/usaf_analysis#3]
camera = picamera.PiCamera()
camera.capture("filename.jpg", bayer= True)

can not have **camera = picamera.PiCamera()**
[microscope_controlAWBISOYC.txt](https://github.com/rwb27/usaf_analysis/files/1575816/microscope_controlAWBISOYC.txt)

**Comment by rwb27** [comment]
I'm not quite sure what you mean by that...  That code snippet was an example of the minimum code you need to save a reaw image.  I just meant that you should change ``bayer=False`` to ``bayer=True`` on the relevant line of the script (which I see you've done).  Is it not working?

**Comment by YenChunLin** [comment]
It is working!
